apiVersion: v1
kind: Pod
metadata:
  name: photo-pod
  namespace: surya-ns
  labels:
    app: photo-app
spec:
  containers:
    - name: photo-container
      image: suryaa112003/photo-studio:v1.1.0
      ports:
        - containerPort: 3000
