apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-deploy
  namespace: surya-ns
  labels:
    app: fitness-label
spec:
  replicas: 8
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: fitness-template-label
  template:
    metadata:
      labels: 
        app: fitness-template-label
    spec:
      containers:
        - name: fitness-cont
          image: muralisocial123/kyndrl-flower-app:v1.1.0
          ports:
            - containerPort: 3015