apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-deploy
  namespace: surya-ns
  labels:
    app: fitness-label
spec:
  replicas: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: fitness-template-label
  template:
    metadata:
      labels: 
        app: fitness-template-label
    spec:
      containers:
        - name: fitness-cont
          image: muralisocial123/fitness-app:v1.0.1
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: fitness-deploy-svc
  namespace: surya-ns
spec:
  selector:
    app: fitness-template-label
  ports:
    - port: 3001 # It is a service port number. We are using to expose the application to internet
      targetPort: 5000 # Same port number as container port
      protocol: TCP
  type: NodePort
