apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-deploy
  namespace: surya-ns
  labels:
    app: fitness-label
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: fitness-template-label
  template:
    metadata:
      label: 
        app: fitness-template-label
    spec:
      containers:
        - name: fitness-cont
          image: muralisocial123/fitness-app:v1.0.1
          ports:
            - containerPort: 3000